# Generated by Django 5.0.3 on 2024-03-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
